title: Project
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: thumbnail
            field:
              container: assets
              type: assets
              display: Thumbnail
          -
            handle: project_url
            field:
              type: text
              display: 'Project URL'
              instructions: 'External URL to the live project website'
          -
            handle: content
            field:
              type: markdown
              display: Content
              localizable: true
          -
            handle: template
            field:
              type: template
              display: Template
              localizable: true
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: date
            field:
              type: date
              required: true
              default: now
              validate:
                - required
          -
            handle: parent
            field:
              type: entries
              collections:
                - projects
              max_items: 1
              listable: false
              localizable: true
